"""init

Revision ID: 4a8fdb768c95
Revises: 
Create Date: 2023-08-05 21:11:12.156351

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '4a8fdb768c95'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('parse_website_url',
                    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
                    sa.Column('url', sa.Text(), nullable=False),
                    sa.Column('text_callback', sa.Text(), nullable=False),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('text_callback'),
                    sa.UniqueConstraint('url')
                    )
    op.create_table('users',
                    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
                    sa.Column('user_id', sa.BigInteger(), nullable=False),
                    sa.Column('username', sa.Text(), nullable=False),
                    sa.Column('balance', sa.Float(), nullable=False),
                    sa.Column('role', sa.Enum('USER', 'ADMIN', 'SUPER_ADMIN', name='role'), nullable=False),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('user_id'),
                    sa.UniqueConstraint('username')
                    )
    op.create_table('mods',
                    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
                    sa.Column('user_id', sa.BigInteger(), nullable=False),
                    sa.Column('mode', sa.String(length=30), nullable=False),
                    sa.Column('callback', sa.Text(), nullable=False),
                    sa.ForeignKeyConstraint(['callback'], ['parse_website_url.text_callback'], ),
                    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('mods')
    op.drop_table('users')
    op.drop_table('parse_website_url')
    # ### end Alembic commands ###
